version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devserver:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        #VARIANT: 3.10
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "/usr/sbin/sshd -D && sleep infinity"

    # Runs devserver on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
    - proxy-net
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    ports:
    - "2222:22"
    # Use "forwardPorts" in **devcontainer.json** to forward an devserver port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
networks:
  proxy-net:
    external:
      name: airflow_default